export const Routes = {
  MAIN: "MAIN",
  ERROR_NOT_FOUND: "error_not_found",

  ACCOUNT: "account",
  ACCOUNT_INFO: "account_info",
  ACCOUNT_SETTINGS: "ACCOUNT_SETTINGS",
  ACCOUNT_SETTINGS_LANGUAGE: "account_settings_language",

  WALLET_START: "WALLET_START",

  WITHDRAW_START: "WITHDRAW_START",
  WITHDRAW_AMOUNT: "WITHDRAW_AMOUNT",
  WITHDRAW_ADDRESS: "WITHDRAW_ADDRESS",
  WITHDRAW_WALLET: "WITHDRAW_WALLET",
  WITHDRAW_WALLET_SELECT: (s?: string) => `WITHDRAW_WALLET__${s || ""}`,
  WITHDRAW_CONFIRM: "WITHDRAW_CONFIRM",
  WITHDRAW_FULFILLED: "WITHDRAW_FULFILLED",
  WITHDRAW_FAILED: "WITHDRAW_FAILED",
  WITHDRAW__CONFIRM: "WITHDRAW__CONFIRM",
  WITHDRAW__CANCEL: "WITHDRAW__CANCEL",

  DEPOSIT_START: "DEPOSIT_START",
  DEPOSIT_WALLET: "DEPOSIT_WALLET",
  DEPOSIT_WALLET_SELECT: (s?: string) => `DEPOSIT_WALLET__${s || ""}`,
  DEPOSIT_ADDRESS: "DEPOSIT_ADDRESS",

  EXCHANGE: "exchange",
  DASHBOARD_START: "dashboard_start",
};
